name: deploy

on:
    push:
        branches: [ master ]

env:
    IMAGE_NAME: scrapers
    IMAGE_TAG: dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{secrets.DEV_REGISTRY_URL}}
                  username: ${{secrets.DEV_REGISTRY_USERNAME}}
                  password: ${{secrets.DEV_REGISTRY_PASSWORD}}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      ${{secrets.DEV_REGISTRY_URL}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
